name: CI

on: 
  workflow_dispatch:  
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEX_VERSION: ${{ matrix.basex }}
      BASEX_S: ${{ matrix.basex }}
      GITHUB_CONTEXT: ${{ toJSON(github) }}
    strategy:
      matrix:
        java: ["8"]
        basex: ["9.7.3"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          architecture: x64
      - name: Display the path
        run: echo $PATH
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: install basex
        run |
          curl https://files.basex.org/releases/9.7.3/BaseX973.zip | jar xv
          /basex/bin/basex -t foo


