name: Unit tests BaseX

on: 
  workflow_dispatch:  
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEX_VERSION: ${{ matrix.basex }}

    strategy:
      matrix:
        java: ["8"]
        basex: ["9.7.3"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          architecture: x64

      - name: determine BaseX download location
        shell: bash
        run: |
          BASEX1= ${BASEX_VERSION//.} # replace all dots
          echo "BASEX1=${BASEX1}" >> $GITHUB_ENV
          echo "${{ format('{{https://files.basex.org/releases/{0}/BaseX{1}.zip}}', matrix.basex, env.BASEX1) }}"

      - name: print env
        run: env

      - name: Install BaseX
        run: curl https://files.basex.org/releases/9.7.3/BaseX973.zip | jar xv && chmod a+x basex/bin/*
      
      - name: install package
        run: ./basex/bin/basex -c"repo install https://github.com/expkg-zone58/metadata-extract/releases/download/v1.3.5/metadata-extractor-1.3.5.xar"
     
      - name: run basex tests
        run: ./basex/bin/basex -t src/test





