name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEX_VERSION: ${{ matrix.basex }}
    strategy:
      matrix:
        java: ["8", "17"]
        basex: ["9.7", "9.7.3"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          architecture: x64
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
